### ISSUE TITLE
Sass not being compiled from scss to css

### ISSUE THREAD

**Issue by lmanzurv** [boscoh/sassin#4]
Sass string is being compiled to scss but not to css directly. Must execute manual compilation

**Comment by lmanzurv** [comment]
Ok, I found that I had to use compile_with_scss instead of compile to obtain css directly from sass. Please update documentation to reflect this.

**Comment by boscoh** [comment]
To clarify sassin.compile() compiles .sass code directly to css if no special SCSS-like extensions (variables, mixins) are used. Otherwise it compiles to .scss.

sassin.compile_with_scss() is a two-step compilation. It calls sassin.compile() to compile to scss then it attempts to call pyscss to compile the scss to css.

Cheers, Bosco

**Comment by lmanzurv** [comment]
Yes, I noticed that after reading sassin's code. It is not obvious from the documentation. On the other hand, is there any way to have some sort of sassin.compile_with_scss_from_file() function?

**Comment by boscoh** [comment]
I purposely mad a simple string-based API. This way, you can always wrap it with your own file-or-streaming function. It doesn't work well the other way around.
